### ISSUE TITLE
Yarn tests fail when building from source - potential timezone issue

### ISSUE THREAD

**Issue by svet-b** [yesoreyeram/grafana-infinity-datasource#486]
## **Describe the bug**

Following the instructions in https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/CONTRIBUTING.md, I am able to successfully build the plugin (e.g. with `yarn watch`). But when running `yarn test` or `yarn build`, the tests fail. All failing tests are due to mismatched timestamps.

## **Steps to reproduce**

Check out code from git (either `main` branch of `v1.2.0` tag). Run `yarn` and then `yarn test`.

Several tests fail, as timestamps are off by exactly 1 hour with respect to the expected time.

My timezone in CET (UTC+1) and my computer's clock is set to local time. I suspect this is the issue - though haven't had the chance to test with building on a machine in the UTC timezone.

Relevant output from failing tests:
```
 FAIL  src/app/uql.test.ts (8.473 s)
  ● uql › nested array parsing

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 9
    + Received  + 9

      Array [
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 11.1,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 111.1,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 1.1,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 22.2,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 222.2,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 2.2,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 33.3,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 333.3,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 3.3,
        },
      ]

      83 |           | project "timestamp"="series.timestamp", "value"="series.value", "host", "disk", "metricId"
      84 |           | extend "timestamp"=unixtime_milliseconds_todatetime("timestamp")
    > 85 |           | order by "timestamp" asc`,
         |                                                   ^
      86 |         { data }
      87 |       )
      88 |     ).toStrictEqual([

      at next (src/app/uql.test.ts:85:51)
      at fulfilled (node_modules/tslib/tslib.js:114:62)

 FAIL  src/app/parsers/JSONParser.spec.ts (10.16 s)
  ● JSONParser › With Columns & Root Selector

    expect(received).toMatchSnapshot()

    Snapshot name: `JSONParser With Columns & Root Selector 2`

    - Snapshot  - 2
    + Received  + 2

    @@ -36,16 +36,16 @@
            2011-01-01T00:00:00.000Z,
          ],
          Array [
            "baz",
            30,
    -       2012-01-01T00:00:00.000Z,
    +       2011-12-31T23:00:00.000Z,
            2012-01-01T00:00:00.000Z,
          ],
          Array [
            "apple",
            32,
    -       2013-12-25T00:00:00.000Z,
    +       2013-12-24T23:00:00.000Z,
            2013-12-25T00:00:00.000Z,
          ],
        ],
      }

      146 |       },
      147 |       {
    > 148 |         text: 'Year',
          |                                        ^
      149 |         type: 'timestamp',
      150 |         selector: 'year',
      151 |       },

      at Object.<anonymous> (src/app/parsers/JSONParser.spec.ts:148:40)

 › 1 snapshot failed.
 FAIL  src/app/parsers/XMLParser.spec.ts (10.436 s)
  ● XMLParser › Basic XML

    expect(received).toMatchSnapshot()

    Snapshot name: `XMLParser Basic XML 3`

    - Snapshot  - 2
    + Received  + 2

    @@ -19,14 +19,14 @@
        "name": "",
        "rows": Array [
          Array [
            2553517.5573549946,
            "hello",
    -       2021-11-12T00:00:00.000Z,
    +       2021-11-11T23:00:00.000Z,
          ],
          Array [
            2552517.557354985,
            "world",
    -       2021-11-11T00:00:00.000Z,
    +       2021-11-10T23:00:00.000Z,
          ],
        ],
      }

      106 |         text: 'foo',
      107 |         type: 'string',
    > 108 |       },
          |                   ^
      109 |       {
      110 |         selector: 'e3',
      111 |         text: 'date',

      at Object.<anonymous> (src/app/parsers/XMLParser.spec.ts:108:39)

 › 1 snapshot failed.
 PASS  src/components/QueryColumnItem.test.tsx (46.545 s)
 PASS  src/components/SourceSelector.test.tsx (38.821 s)
 PASS  src/app/variablesQuery/index.test.ts (37.296 s)
 PASS  src/app/variablesQuery/VariableQuery.spec.ts (37.528 s)
 PASS  src/components/TypeSelector.test.tsx (48.161 s)
 PASS  src/components/FormatSelector.test.tsx (48.814 s)
 PASS  src/app/UQLProvider.test.ts
 PASS  src/components/GlobalQuerySelector.test.tsx
 PASS  src/app/parsers/JSONParser_JSONPath.spec.ts
 PASS  src/app/variablesQuery/Collection.spec.ts
 PASS  src/app/parsers/JSONParser.2.spec.ts
 PASS  src/app/parsers/utils.spec.ts
 PASS  src/app/variablesQuery/Join.spec.ts
 PASS  src/app/GROQProvider.test.ts
 PASS  src/app/variablesQuery/CollectionLookup.spec.ts
 PASS  src/app/variablesQuery/UnixTimeStamp.spec.ts
 PASS  src/components/JSONOptionsEditor.test.tsx
 PASS  src/app/parsers/CSVParser.spec.ts
 PASS  src/app/variablesQuery/Random.spec.ts
 PASS  src/app/variablesQuery/utils.spec.ts
 PASS  src/datasource.spec.ts (51.739 s)

Summary of all failing tests
 FAIL  src/app/uql.test.ts (8.473 s)
  ● uql › nested array parsing

    expect(received).toStrictEqual(expected) // deep equality

    - Expected  - 9
    + Received  + 9

      Array [
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 11.1,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 111.1,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T21:38:20.000Z,
    +     "timestamp": 2069-11-11T22:38:20.000Z,
          "value": 1.1,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 22.2,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 222.2,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T22:38:20.000Z,
    +     "timestamp": 2069-11-11T23:38:20.000Z,
          "value": 2.2,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3F",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 33.3,
        },
        Object {
          "disk": "DISK-F1266E1D0AAC2C3D",
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.disk.avail",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 333.3,
        },
        Object {
          "disk": undefined,
          "host": "HOST-F1266E1D0AAC2C3C",
          "metricId": "builtin:host.cpu.idle",
    -     "timestamp": 2069-11-11T23:38:20.000Z,
    +     "timestamp": 2069-11-12T00:38:20.000Z,
          "value": 3.3,
        },
      ]

      83 |           | project "timestamp"="series.timestamp", "value"="series.value", "host", "disk", "metricId"
      84 |           | extend "timestamp"=unixtime_milliseconds_todatetime("timestamp")
    > 85 |           | order by "timestamp" asc`,
         |                                                   ^
      86 |         { data }
      87 |       )
      88 |     ).toStrictEqual([

      at next (src/app/uql.test.ts:85:51)
      at fulfilled (node_modules/tslib/tslib.js:114:62)

 FAIL  src/app/parsers/JSONParser.spec.ts (10.16 s)
  ● JSONParser › With Columns & Root Selector

    expect(received).toMatchSnapshot()

    Snapshot name: `JSONParser With Columns & Root Selector 2`

    - Snapshot  - 2
    + Received  + 2

    @@ -36,16 +36,16 @@
            2011-01-01T00:00:00.000Z,
          ],
          Array [
            "baz",
            30,
    -       2012-01-01T00:00:00.000Z,
    +       2011-12-31T23:00:00.000Z,
            2012-01-01T00:00:00.000Z,
          ],
          Array [
            "apple",
            32,
    -       2013-12-25T00:00:00.000Z,
    +       2013-12-24T23:00:00.000Z,
            2013-12-25T00:00:00.000Z,
          ],
        ],
      }

      146 |       },
      147 |       {
    > 148 |         text: 'Year',
          |                                        ^
      149 |         type: 'timestamp',
      150 |         selector: 'year',
      151 |       },

      at Object.<anonymous> (src/app/parsers/JSONParser.spec.ts:148:40)

 FAIL  src/app/parsers/XMLParser.spec.ts (10.436 s)
  ● XMLParser › Basic XML

    expect(received).toMatchSnapshot()

    Snapshot name: `XMLParser Basic XML 3`

    - Snapshot  - 2
    + Received  + 2

    @@ -19,14 +19,14 @@
        "name": "",
        "rows": Array [
          Array [
            2553517.5573549946,
            "hello",
    -       2021-11-12T00:00:00.000Z,
    +       2021-11-11T23:00:00.000Z,
          ],
          Array [
            2552517.557354985,
            "world",
    -       2021-11-11T00:00:00.000Z,
    +       2021-11-10T23:00:00.000Z,
          ],
        ],
      }

      106 |         text: 'foo',
      107 |         type: 'string',
    > 108 |       },
          |                   ^
      109 |       {
      110 |         selector: 'e3',
      111 |         text: 'date',

      at Object.<anonymous> (src/app/parsers/XMLParser.spec.ts:108:39)


Snapshot Summary
 › 2 snapshots failed from 2 test suites. Inspect your code changes or re-run jest with `-u` to update them.

Test Suites: 3 failed, 21 passed, 24 total
Tests:       3 failed, 86 passed, 89 total
Snapshots:   2 failed, 36 passed, 38 total
Time:        53 s
Ran all test suites with tests matching "".
✖ Tests failed
```

## **Version Details:**

- Grafana version : N/A
- Plugin code version : `v1.2.0` tag or current `main` branch
- Yarn: v1.22.10

**Comment by svet-b** [comment]
Thanks @yesoreyeram for the pointer - unfortunately I didn't see that SO page in my googling, but your proposed solution is spot on!

I'm going to close this as I imagine it's not a widespread issue. Up to you whether `package.json` in the codebase itself should be tweaked - I'm not sure what the potential trade-offs there are.
