### ISSUE TITLE
[Bug] OAuth2 Authentication throws error

### ISSUE THREAD

**Issue by LudwigJan** [yesoreyeram/grafana-infinity-datasource#681]
## **Describe the bug**
![Screenshot 2023-09-27 at 09 12 17](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/129760848/6779296b-1b1c-44d9-8d49-2f49db67978c)

I need to use the OAuth2 Authentication method.

As soon as I click the "Save & Test" button after entering a value into one of the fields (Client ID, Client Secret, Token URL), the error pops up:
 
![Screenshot 2023-09-27 at 09 15 03](https://github.com/yesoreyeram/grafana-infinity-datasource/assets/129760848/1e94b3da-d651-46b0-aa3b-a8278dd3905d)

An unexpected error happened
-> Details
TypeError: Cannot assign to read only property 'oauth2_type' of object '#<Object>'

    at fO (https://flexpwr.grafana.net/public/plugins/yesoreyeram-infinity-datasource/module.js?_cache=2.0.0:3:1780081)
    at div
    at DO (https://flexpwr.grafana.net/public/plugins/yesoreyeram-infinity-datasource/module.js?_cache=2.0.0:3:1795465)
    at div
    at div
    at eval (https://flexpwr.grafana.net/public/plugins/yesoreyeram-infinity-datasource/module.js?_cache=2.0.0:3:1829645)
    at div
    at ft (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:75:2617)
    at c (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:1:172)
    at form
    at xt (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:83:1917)
    at de (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:83:1468)
    at l (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:671:702)
    at div
    at div
    at div
    at div
    at V (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:137:79770)
    at s (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:201:30028)
    at div
    at D (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:671:4385)
    at Tt (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:83:5054)
    at It (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:83:5466)
    at xe (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:23511)
    at xe (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:25706)
    at zt (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/Connections.779e973c27a8491cf352.js:91:2067)
    at Suspense
    at o (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:201:118944)
    at va (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:385:333)
    at xe (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:23511)
    at Wi (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:220:4723)
    at wn (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:220:10214)
    at hu (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:11733)
    at xe (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:25706)
    at div
    at div
    at main
    at div
    at zr (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:382:2442)
    at Wi (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:220:4723)
    at wn (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:220:10214)
    at qt (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:220:9603)
    at Uu (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:12032)
    at xe (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:229:19683)
    at div
    at c (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:221:13282)
    at v (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:37:13792)
    at h (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:672:177297)
    at l (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:1088:19771)
    at o (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:201:118944)
    at m (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:201:119453)
    at E (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/4110.1c0cb94784baffd0ec0a.js:198:117915)
    at qa (https://grafana-assets.grafana.net/grafana/10.2.0-60982/public/build/7769.62eb7c7db66dcb2bcf38.js:396:127)

## **Version Details:**
- Grafana version : 10.2.0-60982
- Plugin version : v2.0.0

## **Additional context**

Am I missing something here? What can I do to make that authentication method work.

**Comment by jakerobinson** [comment]
I receive the same exception even when attempting to paste in the client_secret.

**Comment by paige-muon** [comment]
This is the same as the bug I opened a few weeks ago: https://github.com/yesoreyeram/grafana-infinity-datasource/issues/668

**Comment by alexandredavi** [comment]
+1

**Comment by raphael5178** [comment]
+1
